[package]
name = "getter-cache"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["concurrent"]
concurrent = []

[dependencies]
# Workspace dependencies
tokio = { workspace = true, features = ["fs"] }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
once_cell = { workspace = true }

# Internal dependencies
getter-utils = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"