[package]
name = "getter-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }

# Internal dependencies
getter-utils = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"