//! Installed-inventory autogen planning for generated fallback repositories.
//!
//! This module is pure domain logic: platform adapters provide installed
//! inventory facts, while getter decides package ids, generated Lua shape,
//! deterministic paths, and preview DTOs.

use crate::repository::REPO_API_VERSION_V1;
use crate::{InstalledTarget, PackageId, PackageKind, RepositoryId, RepositoryPriority};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeSet, HashMap};
use std::path::PathBuf;

pub const INSTALLED_INVENTORY_FORMAT: &str = "upgradeall-installed-inventory";
pub const INSTALLED_INVENTORY_VERSION: u32 = 1;
pub const AUTOGEN_MANIFEST_VERSION: u32 = 1;
pub const LOCAL_REPOSITORY_ID: &str = "local";
pub const LOCAL_REPOSITORY_NAME: &str = "Local";
pub const LOCAL_AUTOGEN_REPOSITORY_ID: &str = "local_autogen";
pub const LOCAL_AUTOGEN_REPOSITORY_NAME: &str = "UpgradeAll Local Autogen";
pub const GENERATED_MARKER: &str = "@generated by UpgradeAll getter local_autogen";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InstalledInventory {
    pub format: String,
    pub version: u32,
    #[serde(default)]
    pub items: Vec<InstalledInventoryItem>,
}

impl InstalledInventory {
    pub fn new(items: Vec<InstalledInventoryItem>) -> Self {
        Self {
            format: INSTALLED_INVENTORY_FORMAT.to_owned(),
            version: INSTALLED_INVENTORY_VERSION,
            items,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum InstalledInventoryItem {
    #[serde(alias = "android")]
    AndroidPackage {
        package_name: String,
        #[serde(default)]
        label: Option<String>,
        #[serde(default)]
        version_name: Option<String>,
        #[serde(default)]
        version_code: Option<i64>,
    },
    #[serde(alias = "magisk")]
    MagiskModule {
        module_id: String,
        #[serde(default)]
        name: Option<String>,
        #[serde(default)]
        version_name: Option<String>,
        #[serde(default)]
        version_code: Option<i64>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenPlan {
    pub repository_id: RepositoryId,
    pub repository_name: String,
    pub repository_priority: RepositoryPriority,
    pub candidates: Vec<AutogenCandidate>,
    pub skipped: Vec<AutogenSkip>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenCandidate {
    pub package_id: PackageId,
    pub name: String,
    pub installed: InstalledTarget,
    pub relative_path: PathBuf,
    pub content: String,
    pub content_hash: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenSkip {
    pub package_id: PackageId,
    pub reason: AutogenSkipReason,
    #[serde(default)]
    pub repository_id: Option<RepositoryId>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AutogenSkipReason {
    DuplicateInventoryItem,
    CoveredByHigherPriorityRepository,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenManifest {
    pub version: u32,
    pub repository_id: RepositoryId,
    pub packages: Vec<AutogenManifestEntry>,
}

impl AutogenManifest {
    pub fn from_candidates(candidates: &[AutogenCandidate]) -> Self {
        Self {
            version: AUTOGEN_MANIFEST_VERSION,
            repository_id: RepositoryId::new(LOCAL_AUTOGEN_REPOSITORY_ID)
                .expect("local_autogen is a valid repository id"),
            packages: candidates
                .iter()
                .map(|candidate| AutogenManifestEntry {
                    package_id: candidate.package_id.clone(),
                    relative_path: candidate.relative_path.clone(),
                    content_hash: candidate.content_hash.clone(),
                })
                .collect(),
        }
    }

    pub fn package(&self, package_id: &PackageId) -> Option<&AutogenManifestEntry> {
        self.packages
            .iter()
            .find(|entry| &entry.package_id == package_id)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenManifestEntry {
    pub package_id: PackageId,
    pub relative_path: PathBuf,
    pub content_hash: String,
}

#[derive(Debug, thiserror::Error)]
pub enum AutogenError {
    #[error("unsupported installed inventory format '{0}'")]
    UnsupportedInventoryFormat(String),
    #[error("unsupported installed inventory version {found}; expected {expected}")]
    UnsupportedInventoryVersion { found: u32, expected: u32 },
    #[error("installed inventory item has an empty identity")]
    EmptyIdentity,
    #[error("failed to construct package id from installed inventory: {0}")]
    PackageId(#[from] crate::PackageIdError),
}

/// Build a deterministic local_autogen preview from installed inventory.
///
/// `covered_packages` contains package ids already supplied by repositories with
/// priority higher than `local_autogen`. Those packages are skipped so generated
/// fallback files do not compete with user-authored `local` or upstream package
/// files.
pub fn plan_local_autogen(
    inventory: &InstalledInventory,
    covered_packages: &HashMap<PackageId, RepositoryId>,
) -> Result<AutogenPlan, AutogenError> {
    validate_installed_inventory(inventory)?;
    let mut seen = BTreeSet::new();
    let mut candidates = Vec::new();
    let mut skipped = Vec::new();

    for item in &inventory.items {
        let candidate = candidate_from_inventory_item(item)?;
        if !seen.insert(candidate.package_id.to_string()) {
            skipped.push(AutogenSkip {
                package_id: candidate.package_id,
                reason: AutogenSkipReason::DuplicateInventoryItem,
                repository_id: None,
            });
            continue;
        }
        if let Some(repository_id) = covered_packages.get(&candidate.package_id) {
            skipped.push(AutogenSkip {
                package_id: candidate.package_id,
                reason: AutogenSkipReason::CoveredByHigherPriorityRepository,
                repository_id: Some(repository_id.clone()),
            });
            continue;
        }
        candidates.push(candidate);
    }

    candidates.sort_by_key(|candidate| candidate.package_id.to_string());
    skipped.sort_by_key(|skip| skip.package_id.to_string());

    Ok(AutogenPlan {
        repository_id: RepositoryId::new(LOCAL_AUTOGEN_REPOSITORY_ID)
            .expect("local_autogen is a valid repository id"),
        repository_name: LOCAL_AUTOGEN_REPOSITORY_NAME.to_owned(),
        repository_priority: RepositoryPriority::LOCAL_AUTOGEN,
        candidates,
        skipped,
    })
}

pub fn validate_installed_inventory(inventory: &InstalledInventory) -> Result<(), AutogenError> {
    if inventory.format != INSTALLED_INVENTORY_FORMAT {
        return Err(AutogenError::UnsupportedInventoryFormat(
            inventory.format.clone(),
        ));
    }
    if inventory.version != INSTALLED_INVENTORY_VERSION {
        return Err(AutogenError::UnsupportedInventoryVersion {
            found: inventory.version,
            expected: INSTALLED_INVENTORY_VERSION,
        });
    }
    Ok(())
}

pub fn local_autogen_repo_toml() -> String {
    repo_toml(
        LOCAL_AUTOGEN_REPOSITORY_ID,
        LOCAL_AUTOGEN_REPOSITORY_NAME,
        RepositoryPriority::LOCAL_AUTOGEN,
    )
}

pub fn local_repo_toml() -> String {
    repo_toml(
        LOCAL_REPOSITORY_ID,
        LOCAL_REPOSITORY_NAME,
        RepositoryPriority::LOCAL,
    )
}

fn repo_toml(id: &str, name: &str, priority: RepositoryPriority) -> String {
    format!(
        "id = \"{id}\"\nname = \"{name}\"\npriority = {}\napi_version = \"{REPO_API_VERSION_V1}\"\n",
        priority.value()
    )
}

pub fn generated_file_is_managed(content: &str) -> bool {
    content
        .lines()
        .next()
        .is_some_and(|line| line.contains(GENERATED_MARKER))
}

pub fn content_hash(content: &str) -> String {
    format!("fnv1a64:{:016x}", fnv1a64(content.as_bytes()))
}

fn candidate_from_inventory_item(
    item: &InstalledInventoryItem,
) -> Result<AutogenCandidate, AutogenError> {
    match item {
        InstalledInventoryItem::AndroidPackage {
            package_name,
            label,
            ..
        } => {
            let package_name = non_empty(package_name)?;
            let package_id = PackageId::new(PackageKind::Android, package_name)?;
            let name = label
                .as_deref()
                .filter(|label| !label.trim().is_empty())
                .unwrap_or(package_name)
                .to_owned();
            let installed = InstalledTarget::AndroidPackage {
                package_name: package_name.to_owned(),
            };
            let relative_path = package_relative_path(&package_id);
            let content = render_package_lua(&package_id, &name, &installed);
            let content_hash = content_hash(&content);
            Ok(AutogenCandidate {
                package_id,
                name,
                installed,
                relative_path,
                content,
                content_hash,
            })
        }
        InstalledInventoryItem::MagiskModule {
            module_id, name, ..
        } => {
            let module_id = non_empty(module_id)?;
            let package_id = PackageId::new(PackageKind::Magisk, module_id)?;
            let name = name
                .as_deref()
                .filter(|name| !name.trim().is_empty())
                .unwrap_or(module_id)
                .to_owned();
            let installed = InstalledTarget::MagiskModule {
                module_id: module_id.to_owned(),
            };
            let relative_path = package_relative_path(&package_id);
            let content = render_package_lua(&package_id, &name, &installed);
            let content_hash = content_hash(&content);
            Ok(AutogenCandidate {
                package_id,
                name,
                installed,
                relative_path,
                content,
                content_hash,
            })
        }
    }
}

fn non_empty(value: &str) -> Result<&str, AutogenError> {
    let value = value.trim();
    if value.is_empty() {
        Err(AutogenError::EmptyIdentity)
    } else {
        Ok(value)
    }
}

pub fn package_relative_path(package_id: &PackageId) -> PathBuf {
    let mut path = PathBuf::from("packages");
    path.push(package_id.kind().as_str());
    path.push(format!("{}.lua", package_id.name()));
    path
}

fn render_package_lua(package_id: &PackageId, name: &str, installed: &InstalledTarget) -> String {
    let installed_lua = match installed {
        InstalledTarget::AndroidPackage { package_name } => format!(
            "{{ kind = \"android_package\", package_name = {} }}",
            lua_string(package_name)
        ),
        InstalledTarget::MagiskModule { module_id } => format!(
            "{{ kind = \"magisk_module\", module_id = {} }}",
            lua_string(module_id)
        ),
        InstalledTarget::Generic { id } => {
            format!("{{ kind = \"generic\", id = {} }}", lua_string(id))
        }
    };

    format!(
        "-- {GENERATED_MARKER}\nreturn package_def {{\n  id = {},\n  name = {},\n  installed = {{\n    {installed_lua},\n  }},\n}}\n",
        lua_string(&package_id.to_string()),
        lua_string(name)
    )
}

fn lua_string(value: &str) -> String {
    let mut escaped = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            other => escaped.push(other),
        }
    }
    escaped.push('"');
    escaped
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

#[cfg(test)]
mod tests {
    use super::*;
    #[cfg(feature = "lua")]
    use crate::lua::evaluate_package_file;
    #[cfg(feature = "lua")]
    use crate::repository::RepositoryLayout;
    #[cfg(feature = "lua")]
    use std::fs;

    #[test]
    fn preview_generates_deterministic_android_package_lua() {
        let inventory = InstalledInventory::new(vec![InstalledInventoryItem::AndroidPackage {
            package_name: "org.fdroid.fdroid".to_owned(),
            label: Some("F-Droid".to_owned()),
            version_name: Some("1.20.0".to_owned()),
            version_code: Some(1020000),
        }]);

        let plan = plan_local_autogen(&inventory, &HashMap::new()).unwrap();

        assert_eq!(plan.repository_id.as_str(), LOCAL_AUTOGEN_REPOSITORY_ID);
        assert_eq!(plan.repository_priority, RepositoryPriority::LOCAL_AUTOGEN);
        assert_eq!(plan.candidates.len(), 1);
        let candidate = &plan.candidates[0];
        assert_eq!(
            candidate.package_id.to_string(),
            "android/org.fdroid.fdroid"
        );
        assert_eq!(
            candidate.relative_path,
            PathBuf::from("packages/android/org.fdroid.fdroid.lua")
        );
        assert!(candidate.content.contains(GENERATED_MARKER));
        assert!(candidate.content.contains("package_def"));
        assert_eq!(candidate.content_hash, content_hash(&candidate.content));
    }

    #[test]
    fn preview_skips_packages_covered_by_higher_priority_repositories() {
        let package_id: PackageId = "android/org.fdroid.fdroid".parse().unwrap();
        let mut covered = HashMap::new();
        covered.insert(package_id, RepositoryId::new("official").unwrap());
        let inventory = InstalledInventory::new(vec![InstalledInventoryItem::AndroidPackage {
            package_name: "org.fdroid.fdroid".to_owned(),
            label: Some("F-Droid".to_owned()),
            version_name: None,
            version_code: None,
        }]);

        let plan = plan_local_autogen(&inventory, &covered).unwrap();

        assert!(plan.candidates.is_empty());
        assert_eq!(plan.skipped.len(), 1);
        assert_eq!(
            plan.skipped[0].reason,
            AutogenSkipReason::CoveredByHigherPriorityRepository
        );
        assert_eq!(
            plan.skipped[0]
                .repository_id
                .as_ref()
                .map(RepositoryId::as_str),
            Some("official")
        );
    }

    #[test]
    fn preview_deduplicates_inventory_items() {
        let inventory = InstalledInventory::new(vec![
            InstalledInventoryItem::AndroidPackage {
                package_name: "org.fdroid.fdroid".to_owned(),
                label: Some("F-Droid".to_owned()),
                version_name: None,
                version_code: None,
            },
            InstalledInventoryItem::AndroidPackage {
                package_name: "org.fdroid.fdroid".to_owned(),
                label: Some("F-Droid Duplicate".to_owned()),
                version_name: None,
                version_code: None,
            },
        ]);

        let plan = plan_local_autogen(&inventory, &HashMap::new()).unwrap();

        assert_eq!(plan.candidates.len(), 1);
        assert_eq!(plan.skipped.len(), 1);
        assert_eq!(
            plan.skipped[0].reason,
            AutogenSkipReason::DuplicateInventoryItem
        );
    }

    #[test]
    fn rejects_unsupported_inventory_contracts() {
        let inventory = InstalledInventory {
            format: "other".to_owned(),
            version: INSTALLED_INVENTORY_VERSION,
            items: Vec::new(),
        };

        assert!(matches!(
            plan_local_autogen(&inventory, &HashMap::new()),
            Err(AutogenError::UnsupportedInventoryFormat(_))
        ));
    }

    #[test]
    fn manifest_records_generated_package_hashes() {
        let inventory = InstalledInventory::new(vec![InstalledInventoryItem::AndroidPackage {
            package_name: "org.fdroid.fdroid".to_owned(),
            label: Some("F-Droid".to_owned()),
            version_name: None,
            version_code: None,
        }]);
        let plan = plan_local_autogen(&inventory, &HashMap::new()).unwrap();

        let manifest = AutogenManifest::from_candidates(&plan.candidates);

        assert_eq!(manifest.version, AUTOGEN_MANIFEST_VERSION);
        assert_eq!(manifest.repository_id.as_str(), LOCAL_AUTOGEN_REPOSITORY_ID);
        assert_eq!(manifest.packages.len(), 1);
        assert_eq!(
            manifest.packages[0].content_hash,
            content_hash(&plan.candidates[0].content)
        );
    }

    #[cfg(feature = "lua")]
    #[test]
    fn generated_lua_evaluates_through_package_boundary() {
        let temp = tempfile::tempdir().unwrap();
        let repo = temp.path();
        fs::write(repo.join("repo.toml"), local_autogen_repo_toml()).unwrap();
        fs::create_dir_all(repo.join("packages/android")).unwrap();
        fs::create_dir(repo.join("lib")).unwrap();
        fs::create_dir(repo.join("templates")).unwrap();
        let inventory = InstalledInventory::new(vec![InstalledInventoryItem::AndroidPackage {
            package_name: "org.fdroid.fdroid".to_owned(),
            label: Some("F-Droid \"client\"".to_owned()),
            version_name: None,
            version_code: None,
        }]);
        let candidate = plan_local_autogen(&inventory, &HashMap::new())
            .unwrap()
            .candidates
            .remove(0);
        let package_path = repo.join(&candidate.relative_path);
        fs::write(&package_path, candidate.content).unwrap();

        let layout = RepositoryLayout::load(repo).unwrap();
        let package = evaluate_package_file(&layout, &package_path).unwrap();

        assert_eq!(package.id.to_string(), "android/org.fdroid.fdroid");
        assert_eq!(package.name, "F-Droid \"client\"");
        assert_eq!(
            package.installed,
            vec![InstalledTarget::AndroidPackage {
                package_name: "org.fdroid.fdroid".to_owned(),
            }]
        );
    }

    #[test]
    fn generated_file_marker_identifies_managed_files_only() {
        assert!(generated_file_is_managed(&format!(
            "-- {GENERATED_MARKER}\nreturn {{}}"
        )));
        assert!(!generated_file_is_managed("return {}"));
    }
}
