//! Installed-inventory autogen planning for generated fallback repositories.
//!
//! This module is pure domain logic: platform adapters provide installed
//! inventory facts, while getter decides package ids, generated package
//! directory contents, deterministic paths, and preview DTOs.

use crate::{InstalledTarget, PackageId, PackageKind, RepositoryId, RepositoryPriority};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha512};
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::{Path, PathBuf};

pub const INSTALLED_INVENTORY_FORMAT: &str = "upgradeall-installed-inventory";
pub const INSTALLED_INVENTORY_VERSION: u32 = 1;
pub const AUTOGEN_RECORD_FILE: &str = ".autogen.jsonc";
pub const AUTOGEN_RECORD_VERSION: u32 = 1;
pub const INSTALLED_AUTOGEN_GENERATOR: &str = "installed-inventory";
pub const DEFAULT_AUTOGEN_REPOSITORY_ID: &str = "autogen";
pub const DEFAULT_AUTOGEN_REPOSITORY_NAME: &str = "UpgradeAll Autogen";
pub const GENERATED_MARKER: &str = "@generated by UpgradeAll getter autogen";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InstalledInventory {
    pub format: String,
    pub version: u32,
    #[serde(default)]
    pub items: Vec<InstalledInventoryItem>,
}

impl InstalledInventory {
    pub fn new(items: Vec<InstalledInventoryItem>) -> Self {
        Self {
            format: INSTALLED_INVENTORY_FORMAT.to_owned(),
            version: INSTALLED_INVENTORY_VERSION,
            items,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum InstalledInventoryItem {
    #[serde(alias = "android")]
    AndroidPackage {
        package_name: String,
        #[serde(default)]
        label: Option<String>,
        #[serde(default)]
        version_name: Option<String>,
        #[serde(default)]
        version_code: Option<i64>,
    },
    #[serde(alias = "magisk")]
    MagiskModule {
        module_id: String,
        #[serde(default)]
        name: Option<String>,
        #[serde(default)]
        version_name: Option<String>,
        #[serde(default)]
        version_code: Option<i64>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenPlan {
    pub repository_id: RepositoryId,
    pub repository_name: String,
    pub repository_priority: RepositoryPriority,
    pub candidates: Vec<AutogenCandidate>,
    pub skipped: Vec<AutogenSkip>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenCandidate {
    pub package_id: PackageId,
    pub name: String,
    pub installed: InstalledTarget,
    pub relative_path: PathBuf,
    pub files: Vec<GeneratedPackageFile>,
    pub record: AutogenRecord,
    /// Hash of the serialized `.autogen.jsonc` record content.
    pub content_hash: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GeneratedPackageFile {
    pub relative_path: PathBuf,
    pub content: String,
    pub content_hash: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenRecord {
    pub version: u32,
    pub generator: String,
    pub package_id: PackageId,
    pub output_relative_path: PathBuf,
    pub input: AutogenRecordInput,
    /// Getter-written generated files and their content hashes.
    /// `.autogen.jsonc` itself is intentionally excluded.
    pub files: BTreeMap<String, String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum AutogenRecordInput {
    InstalledAndroidPackage { package_name: String },
    InstalledMagiskModule { module_id: String },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AutogenSkip {
    pub package_id: PackageId,
    pub reason: AutogenSkipReason,
    #[serde(default)]
    pub repository_id: Option<RepositoryId>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AutogenSkipReason {
    DuplicateInventoryItem,
    CoveredByHigherPriorityRepository,
}

#[derive(Debug, thiserror::Error)]
pub enum AutogenError {
    #[error("unsupported installed inventory format '{0}'")]
    UnsupportedInventoryFormat(String),
    #[error("unsupported installed inventory version {found}; expected {expected}")]
    UnsupportedInventoryVersion { found: u32, expected: u32 },
    #[error("installed inventory item has an empty identity")]
    EmptyIdentity,
    #[error("failed to construct package id from installed inventory: {0}")]
    PackageId(#[from] crate::PackageIdError),
    #[error("failed to serialize generated autogen record: {0}")]
    SerializeRecord(#[from] serde_json::Error),
}

/// Build a deterministic installed-autogen preview from installed inventory.
///
/// `covered_packages` contains package ids already supplied by repositories with
/// priority higher than the generated repository. Those packages are skipped so
/// generated fallback directories do not compete with user-authored `local` or
/// upstream package directories.
pub fn plan_installed_autogen(
    inventory: &InstalledInventory,
    covered_packages: &HashMap<PackageId, RepositoryId>,
) -> Result<AutogenPlan, AutogenError> {
    validate_installed_inventory(inventory)?;
    let mut seen = BTreeSet::new();
    let mut candidates = Vec::new();
    let mut skipped = Vec::new();

    for item in &inventory.items {
        let candidate = candidate_from_inventory_item(item)?;
        if !seen.insert(candidate.package_id.to_string()) {
            skipped.push(AutogenSkip {
                package_id: candidate.package_id,
                reason: AutogenSkipReason::DuplicateInventoryItem,
                repository_id: None,
            });
            continue;
        }
        if let Some(repository_id) = covered_packages.get(&candidate.package_id) {
            skipped.push(AutogenSkip {
                package_id: candidate.package_id,
                reason: AutogenSkipReason::CoveredByHigherPriorityRepository,
                repository_id: Some(repository_id.clone()),
            });
            continue;
        }
        candidates.push(candidate);
    }

    candidates.sort_by_key(|candidate| candidate.package_id.to_string());
    skipped.sort_by_key(|skip| skip.package_id.to_string());

    Ok(AutogenPlan {
        repository_id: RepositoryId::new(DEFAULT_AUTOGEN_REPOSITORY_ID)
            .expect("autogen is a valid repository id"),
        repository_name: DEFAULT_AUTOGEN_REPOSITORY_NAME.to_owned(),
        repository_priority: RepositoryPriority::GENERATED_FALLBACK,
        candidates,
        skipped,
    })
}

pub fn validate_installed_inventory(inventory: &InstalledInventory) -> Result<(), AutogenError> {
    if inventory.format != INSTALLED_INVENTORY_FORMAT {
        return Err(AutogenError::UnsupportedInventoryFormat(
            inventory.format.clone(),
        ));
    }
    if inventory.version != INSTALLED_INVENTORY_VERSION {
        return Err(AutogenError::UnsupportedInventoryVersion {
            found: inventory.version,
            expected: INSTALLED_INVENTORY_VERSION,
        });
    }
    Ok(())
}

pub fn content_hash(content: &str) -> String {
    content_hash_bytes(content.as_bytes())
}

pub fn content_hash_bytes(content: &[u8]) -> String {
    let mut hasher = Sha512::new();
    hasher.update(content);
    format!("sha512:{:x}", hasher.finalize())
}

pub fn render_autogen_record(record: &AutogenRecord) -> Result<String, serde_json::Error> {
    serde_json::to_string_pretty(record).map(|mut content| {
        content.push('\n');
        content
    })
}

pub fn package_relative_path(package_id: &PackageId) -> PathBuf {
    package_id.to_string().split('/').collect()
}

fn candidate_from_inventory_item(
    item: &InstalledInventoryItem,
) -> Result<AutogenCandidate, AutogenError> {
    match item {
        InstalledInventoryItem::AndroidPackage {
            package_name,
            label,
            ..
        } => {
            let package_name = non_empty(package_name)?;
            let package_id = PackageId::new(PackageKind::Android, format!("app/{package_name}"))?;
            let name = label
                .as_deref()
                .filter(|label| !label.trim().is_empty())
                .unwrap_or(package_name)
                .to_owned();
            let installed = InstalledTarget::AndroidPackage {
                package_name: package_name.to_owned(),
            };
            let input = AutogenRecordInput::InstalledAndroidPackage {
                package_name: package_name.to_owned(),
            };
            candidate(package_id, name, installed, input)
        }
        InstalledInventoryItem::MagiskModule {
            module_id, name, ..
        } => {
            let module_id = non_empty(module_id)?;
            let package_id = PackageId::new(PackageKind::Magisk, module_id)?;
            let name = name
                .as_deref()
                .filter(|name| !name.trim().is_empty())
                .unwrap_or(module_id)
                .to_owned();
            let installed = InstalledTarget::MagiskModule {
                module_id: module_id.to_owned(),
            };
            let input = AutogenRecordInput::InstalledMagiskModule {
                module_id: module_id.to_owned(),
            };
            candidate(package_id, name, installed, input)
        }
    }
}

fn candidate(
    package_id: PackageId,
    name: String,
    installed: InstalledTarget,
    input: AutogenRecordInput,
) -> Result<AutogenCandidate, AutogenError> {
    let relative_path = package_relative_path(&package_id);
    let files = generated_package_files(&name, &installed)?;
    let record = autogen_record(package_id.clone(), relative_path.clone(), input, &files);
    let content_hash = content_hash(&render_autogen_record(&record)?);
    Ok(AutogenCandidate {
        package_id,
        name,
        installed,
        relative_path,
        files,
        record,
        content_hash,
    })
}

fn generated_package_files(
    name: &str,
    installed: &InstalledTarget,
) -> Result<Vec<GeneratedPackageFile>, AutogenError> {
    let metadata = match installed {
        InstalledTarget::AndroidPackage { package_name } => serde_json::json!({
            "type": "android:app",
            "display_name": name,
            "android": { "package_name": package_name },
        }),
        InstalledTarget::MagiskModule { module_id } => serde_json::json!({
            "type": "magisk:module",
            "display_name": name,
            "magisk": { "module_id": module_id },
        }),
        InstalledTarget::Generic { id } => serde_json::json!({
            "type": "generic",
            "display_name": name,
            "generic": { "id": id },
        }),
    };
    let metadata = render_pretty_json(metadata)?;
    let manifest = String::new();
    let version_lua = render_version_lua(installed);
    Ok(vec![
        generated_file("metadata.jsonc", metadata),
        generated_file("Manifest", manifest),
        generated_file("9999.lua", version_lua),
    ])
}

fn render_pretty_json(value: serde_json::Value) -> Result<String, serde_json::Error> {
    serde_json::to_string_pretty(&value).map(|mut content| {
        content.push('\n');
        content
    })
}

fn generated_file(relative_path: &str, content: String) -> GeneratedPackageFile {
    GeneratedPackageFile {
        relative_path: PathBuf::from(relative_path),
        content_hash: content_hash(&content),
        content,
    }
}

fn autogen_record(
    package_id: PackageId,
    output_relative_path: PathBuf,
    input: AutogenRecordInput,
    files: &[GeneratedPackageFile],
) -> AutogenRecord {
    AutogenRecord {
        version: AUTOGEN_RECORD_VERSION,
        generator: INSTALLED_AUTOGEN_GENERATOR.to_owned(),
        package_id,
        output_relative_path,
        input,
        files: files
            .iter()
            .map(|file| {
                (
                    record_file_key(&file.relative_path),
                    file.content_hash.clone(),
                )
            })
            .collect(),
    }
}

pub fn record_file_key(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn render_version_lua(installed: &InstalledTarget) -> String {
    let installed_lua = match installed {
        InstalledTarget::AndroidPackage { package_name } => format!(
            "{{ kind = \"android_package\", package_name = {} }}",
            lua_string(package_name)
        ),
        InstalledTarget::MagiskModule { module_id } => format!(
            "{{ kind = \"magisk_module\", module_id = {} }}",
            lua_string(module_id)
        ),
        InstalledTarget::Generic { id } => {
            format!("{{ kind = \"generic\", id = {} }}", lua_string(id))
        }
    };

    format!(
        "#!/bin/upa-lua v1\n-- {GENERATED_MARKER}\nreturn package_version {{\n  installed = {{\n    {installed_lua},\n  }},\n}}\n",
    )
}

fn lua_string(value: &str) -> String {
    let mut escaped = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            other => escaped.push(other),
        }
    }
    escaped.push('"');
    escaped
}

fn non_empty(value: &str) -> Result<&str, AutogenError> {
    let value = value.trim();
    if value.is_empty() {
        Err(AutogenError::EmptyIdentity)
    } else {
        Ok(value)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::repository::RepositoryPackageDirectoryLayout;
    use std::fs;

    #[test]
    fn preview_generates_deterministic_android_package_directory() {
        let inventory = InstalledInventory::new(vec![InstalledInventoryItem::AndroidPackage {
            package_name: "org.fdroid.fdroid".to_owned(),
            label: Some("F-Droid".to_owned()),
            version_name: Some("1.20.0".to_owned()),
            version_code: Some(1020000),
        }]);

        let plan = plan_installed_autogen(&inventory, &HashMap::new()).unwrap();

        assert_eq!(plan.repository_id.as_str(), DEFAULT_AUTOGEN_REPOSITORY_ID);
        assert_eq!(
            plan.repository_priority,
            RepositoryPriority::GENERATED_FALLBACK
        );
        assert_eq!(plan.candidates.len(), 1);
        let candidate = &plan.candidates[0];
        assert_eq!(
            candidate.package_id.to_string(),
            "android/app/org.fdroid.fdroid"
        );
        assert_eq!(
            candidate.relative_path,
            PathBuf::from("android/app/org.fdroid.fdroid")
        );
        assert_eq!(candidate.files.len(), 3);
        assert!(candidate
            .files
            .iter()
            .any(|file| file.relative_path == PathBuf::from("metadata.jsonc")
                && file.content.contains("org.fdroid.fdroid")));
        assert!(candidate.files.iter().any(|file| {
            file.relative_path == PathBuf::from("9999.lua")
                && file.content.starts_with("#!/bin/upa-lua v1\n")
                && file.content.contains(GENERATED_MARKER)
        }));
        assert_eq!(candidate.record.package_id, candidate.package_id);
        assert_eq!(candidate.record.files.len(), candidate.files.len());
        assert_eq!(
            candidate.content_hash,
            content_hash(&render_autogen_record(&candidate.record).unwrap())
        );
    }

    #[test]
    fn preview_skips_packages_covered_by_higher_priority_repositories() {
        let package_id: PackageId = "android/app/org.fdroid.fdroid".parse().unwrap();
        let mut covered = HashMap::new();
        covered.insert(package_id, RepositoryId::new("official").unwrap());
        let inventory = InstalledInventory::new(vec![InstalledInventoryItem::AndroidPackage {
            package_name: "org.fdroid.fdroid".to_owned(),
            label: Some("F-Droid".to_owned()),
            version_name: None,
            version_code: None,
        }]);

        let plan = plan_installed_autogen(&inventory, &covered).unwrap();

        assert!(plan.candidates.is_empty());
        assert_eq!(plan.skipped.len(), 1);
        assert_eq!(
            plan.skipped[0].reason,
            AutogenSkipReason::CoveredByHigherPriorityRepository
        );
        assert_eq!(
            plan.skipped[0]
                .repository_id
                .as_ref()
                .map(RepositoryId::as_str),
            Some("official")
        );
    }

    #[test]
    fn preview_deduplicates_inventory_items() {
        let inventory = InstalledInventory::new(vec![
            InstalledInventoryItem::AndroidPackage {
                package_name: "org.fdroid.fdroid".to_owned(),
                label: Some("F-Droid".to_owned()),
                version_name: None,
                version_code: None,
            },
            InstalledInventoryItem::AndroidPackage {
                package_name: "org.fdroid.fdroid".to_owned(),
                label: Some("F-Droid Duplicate".to_owned()),
                version_name: None,
                version_code: None,
            },
        ]);

        let plan = plan_installed_autogen(&inventory, &HashMap::new()).unwrap();

        assert_eq!(plan.candidates.len(), 1);
        assert_eq!(plan.skipped.len(), 1);
        assert_eq!(
            plan.skipped[0].reason,
            AutogenSkipReason::DuplicateInventoryItem
        );
    }

    #[test]
    fn rejects_unsupported_inventory_contracts() {
        let inventory = InstalledInventory {
            format: "other".to_owned(),
            version: INSTALLED_INVENTORY_VERSION,
            items: Vec::new(),
        };

        assert!(matches!(
            plan_installed_autogen(&inventory, &HashMap::new()),
            Err(AutogenError::UnsupportedInventoryFormat(_))
        ));
    }

    #[test]
    fn generated_files_form_a_package_directory_boundary() {
        let temp = tempfile::tempdir().unwrap();
        let repo = temp.path();
        let inventory = InstalledInventory::new(vec![InstalledInventoryItem::AndroidPackage {
            package_name: "org.fdroid.fdroid".to_owned(),
            label: Some("F-Droid".to_owned()),
            version_name: None,
            version_code: None,
        }]);
        let candidate = plan_installed_autogen(&inventory, &HashMap::new())
            .unwrap()
            .candidates
            .remove(0);
        let package_dir = repo.join(&candidate.relative_path);
        fs::create_dir_all(&package_dir).unwrap();
        for file in &candidate.files {
            fs::write(package_dir.join(&file.relative_path), &file.content).unwrap();
        }
        fs::write(
            package_dir.join(AUTOGEN_RECORD_FILE),
            render_autogen_record(&candidate.record).unwrap(),
        )
        .unwrap();

        let layout = RepositoryPackageDirectoryLayout::load(repo).unwrap();

        assert_eq!(layout.packages.len(), 1);
        assert_eq!(
            layout.packages[0].id.to_string(),
            "android/app/org.fdroid.fdroid"
        );
        assert_eq!(layout.packages[0].version_scripts[0].version, "9999");
    }

    #[test]
    fn content_hash_uses_sha512_prefix() {
        assert!(content_hash("hello").starts_with("sha512:"));
    }
}
