[package]
name = "getter-provider"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes.workspace = true
regex = { workspace = true }

# Internal dependencies
getter-utils = { workspace = true }

# For automatic provider registration
ctor = "0.5"
urlencoding = "2.1.3"
hyper.workspace = true
quick-xml.workspace = true

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.4"
