name: Rust Test CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lints checks by Clippy
      uses: giraffate/clippy-action@v1
      with:
        clippy_flags: -- -Dwarnings

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Run test script
      run: ./tests/script/cargo_test.sh
